// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: internal/grpc/golinks.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LinkImagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkImagesRequest) Reset() {
	*x = LinkImagesRequest{}
	mi := &file_internal_grpc_golinks_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkImagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkImagesRequest) ProtoMessage() {}

func (x *LinkImagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_golinks_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkImagesRequest.ProtoReflect.Descriptor instead.
func (*LinkImagesRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_golinks_proto_rawDescGZIP(), []int{0}
}

func (x *LinkImagesRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type LinkImagesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       []string               `protobuf:"bytes,1,rep,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkImagesReply) Reset() {
	*x = LinkImagesReply{}
	mi := &file_internal_grpc_golinks_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkImagesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkImagesReply) ProtoMessage() {}

func (x *LinkImagesReply) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_golinks_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkImagesReply.ProtoReflect.Descriptor instead.
func (*LinkImagesReply) Descriptor() ([]byte, []int) {
	return file_internal_grpc_golinks_proto_rawDescGZIP(), []int{1}
}

func (x *LinkImagesReply) GetMessage() []string {
	if x != nil {
		return x.Message
	}
	return nil
}

var File_internal_grpc_golinks_proto protoreflect.FileDescriptor

var file_internal_grpc_golinks_proto_rawDesc = string([]byte{
	0x0a, 0x1b, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f,
	0x67, 0x6f, 0x6c, 0x69, 0x6e, 0x6b, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x25, 0x0a,
	0x11, 0x4c, 0x69, 0x6e, 0x6b, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x75, 0x72, 0x6c, 0x22, 0x2b, 0x0a, 0x0f, 0x4c, 0x69, 0x6e, 0x6b, 0x49, 0x6d, 0x61, 0x67,
	0x65, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x32, 0x40, 0x0a, 0x07, 0x47, 0x6f, 0x6c, 0x69, 0x6e, 0x6b, 0x73, 0x12, 0x35, 0x0a, 0x0d,
	0x47, 0x65, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x12, 0x12, 0x2e,
	0x4c, 0x69, 0x6e, 0x6b, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x10, 0x2e, 0x4c, 0x69, 0x6e, 0x6b, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x42, 0x0f, 0x5a, 0x0d, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f,
	0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_internal_grpc_golinks_proto_rawDescOnce sync.Once
	file_internal_grpc_golinks_proto_rawDescData []byte
)

func file_internal_grpc_golinks_proto_rawDescGZIP() []byte {
	file_internal_grpc_golinks_proto_rawDescOnce.Do(func() {
		file_internal_grpc_golinks_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_grpc_golinks_proto_rawDesc), len(file_internal_grpc_golinks_proto_rawDesc)))
	})
	return file_internal_grpc_golinks_proto_rawDescData
}

var file_internal_grpc_golinks_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_grpc_golinks_proto_goTypes = []any{
	(*LinkImagesRequest)(nil), // 0: LinkImagesRequest
	(*LinkImagesReply)(nil),   // 1: LinkImagesReply
}
var file_internal_grpc_golinks_proto_depIdxs = []int32{
	0, // 0: Golinks.GetLinkImages:input_type -> LinkImagesRequest
	1, // 1: Golinks.GetLinkImages:output_type -> LinkImagesReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_grpc_golinks_proto_init() }
func file_internal_grpc_golinks_proto_init() {
	if File_internal_grpc_golinks_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_grpc_golinks_proto_rawDesc), len(file_internal_grpc_golinks_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_grpc_golinks_proto_goTypes,
		DependencyIndexes: file_internal_grpc_golinks_proto_depIdxs,
		MessageInfos:      file_internal_grpc_golinks_proto_msgTypes,
	}.Build()
	File_internal_grpc_golinks_proto = out.File
	file_internal_grpc_golinks_proto_goTypes = nil
	file_internal_grpc_golinks_proto_depIdxs = nil
}
