// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: internal/grpc/golinks.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Golinks_GetLinkImages_FullMethodName = "/Golinks/GetLinkImages"
)

// GolinksClient is the client API for Golinks service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GolinksClient interface {
	GetLinkImages(ctx context.Context, in *LinkImagesRequest, opts ...grpc.CallOption) (*LinkImagesReply, error)
}

type golinksClient struct {
	cc grpc.ClientConnInterface
}

func NewGolinksClient(cc grpc.ClientConnInterface) GolinksClient {
	return &golinksClient{cc}
}

func (c *golinksClient) GetLinkImages(ctx context.Context, in *LinkImagesRequest, opts ...grpc.CallOption) (*LinkImagesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LinkImagesReply)
	err := c.cc.Invoke(ctx, Golinks_GetLinkImages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GolinksServer is the server API for Golinks service.
// All implementations must embed UnimplementedGolinksServer
// for forward compatibility.
type GolinksServer interface {
	GetLinkImages(context.Context, *LinkImagesRequest) (*LinkImagesReply, error)
	mustEmbedUnimplementedGolinksServer()
}

// UnimplementedGolinksServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGolinksServer struct{}

func (UnimplementedGolinksServer) GetLinkImages(context.Context, *LinkImagesRequest) (*LinkImagesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLinkImages not implemented")
}
func (UnimplementedGolinksServer) mustEmbedUnimplementedGolinksServer() {}
func (UnimplementedGolinksServer) testEmbeddedByValue()                 {}

// UnsafeGolinksServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GolinksServer will
// result in compilation errors.
type UnsafeGolinksServer interface {
	mustEmbedUnimplementedGolinksServer()
}

func RegisterGolinksServer(s grpc.ServiceRegistrar, srv GolinksServer) {
	// If the following call pancis, it indicates UnimplementedGolinksServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Golinks_ServiceDesc, srv)
}

func _Golinks_GetLinkImages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LinkImagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GolinksServer).GetLinkImages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Golinks_GetLinkImages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GolinksServer).GetLinkImages(ctx, req.(*LinkImagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Golinks_ServiceDesc is the grpc.ServiceDesc for Golinks service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Golinks_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Golinks",
	HandlerType: (*GolinksServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLinkImages",
			Handler:    _Golinks_GetLinkImages_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/grpc/golinks.proto",
}
